export const portfolio = {
  brand: {
    name: 'Bloom Studio',
    mark: 'AP',
    logo: '/logo-portfolio-transparent.png',
    photo: '/me.png',
  },
  owner: {
    name: 'Adhelia Putri Maylani',
    shortName: 'Adhelia',
    role: 'Computer Engineering Student',
    level: 'Thesis Defended',
    className: 'Software Development',
    email: 'aputrimaylani26@gmail.com',
    location: 'Indonesia',
  },
  hero: {
    roles: [
      'Computer Engineering Student',
      'Thesis Defended',
      'Software Development Projects',
      'Open to Work & Projects',
    ],
    intro:
      'A Computer Engineering student at Universitas Indonesia who builds full-stack software, learning tools, data dashboards, and applied web systems.',
    currentQuest:
      'Recently defended an educational cybersecurity game thesis and currently preparing for the next step after graduation.',
  },
  profileHighlights: ['React/Vite', 'Node API', 'Firebase', 'Python'],
  links: {
    github: 'https://github.com/purooo0',
    linkedin: 'https://www.linkedin.com/in/adhelia-putri-maylani-32b063250/',
    cv: '#',
  },
}

export const toolkit = [
  { label: 'React', icon: 'R', color: 'bg-pink-100' },
  { label: 'Vite', icon: 'V', color: 'bg-purple-100' },
  { label: 'Next.js', icon: 'N', color: 'bg-blue-100' },
  { label: 'TypeScript', icon: 'TS', color: 'bg-sky-100' },
  { label: 'Tailwind', icon: 'TW', color: 'bg-cyan-100' },
  { label: 'Node.js', icon: 'JS', color: 'bg-emerald-100' },
  { label: 'Express', icon: 'EX', color: 'bg-lime-100' },
  { label: 'Firebase', icon: 'FB', color: 'bg-orange-100' },
  { label: 'Go', icon: 'GO', color: 'bg-teal-100' },
  { label: 'Gin/GORM', icon: 'GG', color: 'bg-indigo-100' },
  { label: 'Python', icon: 'PY', color: 'bg-yellow-100' },
  { label: 'FastAPI', icon: 'FA', color: 'bg-green-100' },
  { label: 'Streamlit', icon: 'ST', color: 'bg-red-100' },
  { label: 'Pandas', icon: 'PD', color: 'bg-violet-100' },
  { label: 'PostgreSQL', icon: 'PG', color: 'bg-blue-100' },
  { label: 'MySQL', icon: 'MY', color: 'bg-orange-100' },
  { label: 'MongoDB', icon: 'MO', color: 'bg-emerald-100' },
  { label: 'SQLite', icon: 'SQ', color: 'bg-stone-100' },
  { label: 'Phaser', icon: 'PH', color: 'bg-fuchsia-100' },
  { label: 'Tiled', icon: 'TM', color: 'bg-rose-100' },
]

export const projects = [
  {
    id: 'cyber-game',
    title: 'CYBER GAME ARCHITECTURE',
    category: 'THESIS PROJECT',
    description:
      'Educational cybersecurity game with scenario-based missions, Phaser/Tiled maps, scoring, badges, leaderboard, and Firebase-backed progress tracking.',
    tech: ['React', 'TypeScript', 'Phaser', 'Tiled', 'Express', 'Firebase'],
    icon: 'CG',
    headerBg: 'bg-pink-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-pink-100',
    color: '#D94F8C',
    difficulty: 'ADVANCED',
    diffColor: 'bg-pink-100 text-foreground',
    status: 'THESIS',
    year: '2026',
    href: 'https://github.com/purooo0/cyber-game-architecture.git',
  },
  {
    id: 'gizibox',
    title: 'GIZIBOX SYSTEM',
    category: 'IOT DASHBOARD',
    description:
      'Monitoring system for healthy-food vending machines with role-based dashboards, Firebase Authentication, Realtime Database, stock/temperature alerts, and operational history.',
    tech: ['React', 'Vite', 'Express', 'Firebase', 'Recharts'],
    icon: 'GZ',
    headerBg: 'bg-emerald-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-emerald-100',
    color: '#0F9F77',
    difficulty: 'ADVANCED',
    diffColor: 'bg-emerald-100 text-foreground',
    status: 'BUILT',
    year: '2025',
    href: 'https://github.com/purooo0/gizibox-system.git',
  },
  {
    id: 'search-engine',
    title: 'AIRSEARCH ENGINE',
    category: 'INFORMATION RETRIEVAL',
    description:
      'Air pollution search engine that processes PDFs and web pages through scraping, Indonesian text preprocessing, TF-IDF/BM25 indexing, FastAPI search endpoints, and a Next.js UI.',
    tech: ['Python', 'FastAPI', 'SQLite', 'Next.js', 'BM25'],
    icon: 'AS',
    headerBg: 'bg-orange-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-orange-100',
    color: '#E8873D',
    difficulty: 'ADVANCED',
    diffColor: 'bg-orange-100 text-foreground',
    status: 'BUILT',
    year: '2026',
    href: 'https://github.com/purooo0/search-engine.git',
  },
  {
    id: 'sales-pipeline',
    title: 'SALES PIPELINE ANALYZER',
    category: 'DATA DASHBOARD',
    description:
      'Streamlit dashboard for adaptive Excel import, sales opportunity mapping, contract value analysis, win-rate views, pipeline summaries, and professional charting.',
    tech: ['Python', 'Streamlit', 'Pandas', 'Matplotlib', 'openpyxl'],
    icon: 'SP',
    headerBg: 'bg-purple-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-purple-100',
    color: '#6657D8',
    difficulty: 'INTERMEDIATE',
    diffColor: 'bg-purple-100 text-foreground',
    status: 'BUILT',
    year: '2025',
    href: 'https://github.com/purooo0/sales-pipeline-analyzer.git',
  },
  {
    id: 'backend-evermos',
    title: 'BACKEND EVERMOS',
    category: 'REST API',
    description:
      'Go-based e-commerce API with JWT authentication, product/store/category/transaction routes, MySQL persistence, GORM models, and Gin routing.',
    tech: ['Go', 'Gin', 'GORM', 'MySQL', 'JWT'],
    icon: 'BE',
    headerBg: 'bg-blue-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-blue-100',
    color: '#60A5FA',
    difficulty: 'INTERMEDIATE',
    diffColor: 'bg-blue-100 text-foreground',
    status: 'BUILT',
    year: '2025',
    href: 'https://github.com/purooo0/backend-evermos.git',
  },
  {
    id: 'quake-rangers',
    title: 'QUAKERANGERS',
    category: 'EDUCATIONAL APP',
    description:
      'Earthquake education game for children under 12, combining a React/Vite frontend with an Express and MongoDB backend for interactive learning flows.',
    tech: ['React', 'Vite', 'Express', 'MongoDB', 'Tailwind'],
    icon: 'QR',
    headerBg: 'bg-yellow-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-yellow-100',
    color: '#D99E1C',
    difficulty: 'INTERMEDIATE',
    diffColor: 'bg-yellow-100 text-foreground',
    status: 'BUILT',
    year: '2024',
    href: 'https://github.com/purooo0/QuakeRangers.git',
  },
  {
    id: 'spotlite',
    title: 'SPOTLITE',
    category: 'EARLY FULL-STACK PROJECT',
    description:
      'Early music streaming web app concept with playlist exploration, artist information, React frontend, Express backend, Sequelize models, and PostgreSQL database design.',
    tech: ['React', 'Express', 'PostgreSQL', 'Sequelize', 'Tailwind'],
    icon: 'SL',
    headerBg: 'bg-rose-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-rose-100',
    color: '#E05E7A',
    difficulty: 'FOUNDATION',
    diffColor: 'bg-rose-100 text-foreground',
    status: 'EARLY',
    year: '2024',
    href: 'https://github.com/purooo0/SpotLITE.git',
  },
]

export const skills = [
  {
    id: 'frontend',
    label: 'FRONTEND ENGINEERING',
    icon: 'FE',
    level: 4,
    maxLevel: 5,
    description:
      'Building React/Vite and Next.js interfaces for dashboards, educational apps, and search experiences.',
    tech: ['React', 'Vite', 'Next.js', 'TypeScript', 'Tailwind CSS', 'React Router'],
    headerBg: 'bg-pink-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-pink-100',
    color: '#D94F8C',
    xp: 84,
  },
  {
    id: 'backend',
    label: 'BACKEND & API DESIGN',
    icon: 'API',
    level: 4,
    maxLevel: 5,
    description:
      'Creating REST APIs, authentication flows, role-based access, and service layers across Node.js, Express, Go, Gin, and FastAPI.',
    tech: ['Node.js', 'Express', 'Go', 'Gin', 'FastAPI', 'JWT'],
    headerBg: 'bg-purple-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-purple-100',
    color: '#6657D8',
    xp: 82,
  },
  {
    id: 'database',
    label: 'DATABASE & FIREBASE',
    icon: 'DB',
    level: 4,
    maxLevel: 5,
    description:
      'Modeling relational and realtime data for products, users, IoT monitoring, game progress, search documents, and analytics dashboards.',
    tech: ['Firebase', 'MySQL', 'PostgreSQL', 'MongoDB', 'SQLite', 'GORM'],
    headerBg: 'bg-emerald-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-emerald-100',
    color: '#0F9F77',
    xp: 80,
  },
  {
    id: 'data-search',
    label: 'DATA & SEARCH PIPELINES',
    icon: 'IR',
    level: 3,
    maxLevel: 5,
    description:
      'Processing messy Excel files, scraping pages, extracting PDFs, preprocessing Indonesian text, and turning data into searchable or visual outputs.',
    tech: ['Python', 'Pandas', 'Streamlit', 'BeautifulSoup', 'PySastrawi', 'BM25'],
    headerBg: 'bg-orange-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-orange-100',
    color: '#E8873D',
    xp: 76,
  },
  {
    id: 'interactive-learning',
    label: 'INTERACTIVE LEARNING SYSTEMS',
    icon: 'ED',
    level: 4,
    maxLevel: 5,
    description:
      'Designing educational software that translates technical topics into missions, feedback loops, maps, scoring, and dashboards.',
    tech: ['Phaser', 'Tiled', 'Learning Design', 'Game Flow', 'Feedback Analytics'],
    headerBg: 'bg-blue-200',
    cardBg: 'bg-white',
    badgeBg: 'bg-blue-100',
    color: '#60A5FA',
    xp: 81,
  },
]

export const milestones = [
  {
    year: '2026',
    title: 'THESIS DEFENDED',
    description:
      'Completed and defended a Computer Engineering thesis through an educational cybersecurity game built with React, Phaser, Tiled, Express, and Firebase.',
    icon: 'TH',
    accentBg: 'bg-pink-200',
    cardBg: 'bg-white',
    color: '#D94F8C',
    exp: 'UI CTE',
    achievement: 'Thesis defended; graduation process in progress',
  },
  {
    year: '2025-2026',
    title: 'SOFTWARE PROJECT PORTFOLIO',
    description:
      'Built full-stack systems across IoT monitoring, information retrieval, e-commerce APIs, educational apps, and analytics dashboards.',
    icon: 'SW',
    accentBg: 'bg-purple-200',
    cardBg: 'bg-white',
    color: '#6657D8',
    exp: 'PROJECTS',
    achievement: 'Full-stack and data-oriented development',
  },
  {
    year: '2022-Present',
    title: 'UNIVERSITAS INDONESIA',
    description:
      'Studying Computer Engineering, with work spanning web systems, databases, software engineering, information retrieval, and applied learning technology.',
    icon: 'UI',
    accentBg: 'bg-emerald-200',
    cardBg: 'bg-white',
    color: '#0F9F77',
    exp: 'COMPUTER ENGINEERING',
    achievement: 'Cohort 2022',
  },
  {
    year: '2022',
    title: 'SMAS YAPEMRI DEPOK',
    description:
      'Graduated from senior high school before continuing into Computer Engineering at Universitas Indonesia.',
    icon: 'HS',
    accentBg: 'bg-orange-200',
    cardBg: 'bg-white',
    color: '#E8873D',
    exp: 'GRADUATED',
    achievement: 'Academic foundation',
  },
]
